version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cpss-infra"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-92hrahclxkt7"
s3_prefix = "cpss-infra"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
