AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    sammy

    Sample SAM Template for sammy

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5
        MemorySize: 128
        Runtime: nodejs14.x
        Architectures:
            - x86_64

Resources:
# S3 Bucket to store primary submissions
    PrimarySubmissionBucket:
      Type : AWS::S3::Bucket
      Properties:
        BucketName: primary-submission-bucket

# S3 Bucket to store indexed submissions
    IndexedSubmissionBucket:
      Type : AWS::S3::Bucket
      Properties:
        BucketName: indexed-submission-bucket

    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: src/lambda/hello-world/
            Handler: app.lambdaHandler
            Events:
                HelloWorld:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /hello
                        Method: get
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
                EntryPoints:
                    - app.ts

    IPreSigned:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: src/lambda/pre-signed/
            Handler: pre-signed.lambdaHandler
            Events:
                GetPreSignedUrl:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /pre-signed
                        Method: get
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
                EntryPoints:
                    - pre-signed.ts
    ITransform : 
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: src/lambda/transform/
            Handler: transform.lambdaHandler
            Events:
                StudentUploadEvent:
                    Type: S3 # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                      Bucket: !Ref IndexedSubmissionBucket
                      Events: 
                      - s3:ObjectCreated:*
            Policies: 
              - LambdaInvokePolicy:
                  FunctionName: !Ref IUpload

        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
                EntryPoints:
                    - transform.ts
    IUpload : 
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: src/lambda/upload/
            Handler: upload.lambdaHandler
            # Environment:
            #   Variables:
            #     PRIMARY_SUBMISSION_BUCKET: !Ref PrimarySubmissionBucket
            #     INDEXED_SUBMISSION_BUCKET: !Ref IndexedSubmissionBucket
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
                EntryPoints:
                    - upload.ts
    EventInvokeConfig:
        Type: AWS::Lambda::EventInvokeConfig
        Properties:
            FunctionName: !Ref ITransform
            Qualifier: $LATEST
            MaximumEventAgeInSeconds: 60
            MaximumRetryAttempts: 0
            DestinationConfig:
              OnSuccess:
                Destination: !GetAtt IUpload.Arn


Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    BeseAPiEndpoint:
        Description: "Best API Endpoint"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
